#!/bin/bash
if grep -Fq "/etc/racoon/remote/*.conf" /etc/racoon/racoon.conf
then
  echo "Already Patched"
else
echo "going to patch the file"
sudo patch /etc/racoon/racoon.conf <<EOF
--- /etc/racoon.orig/racoon.conf  2009-06-23 09:09:08.000000000 +0200
+++ /etc/racoon/racoon.conf   2009-12-11 13:52:11.000000000 +0100
@@ -135,4 +135,5 @@
 # by including all files matching /var/run/racoon/*.conf
 # This line should be added at the end of the racoon.conf file
 # so that settings such as timer values will be appropriately applied.
+include "/etc/racoon/remote/*.conf" ;
 include "/var/run/racoon/*.conf" ;
EOF

fi

echo 'Fixing VPN configurations'
sudo rm -vf /etc/racoon/remote/*
sudo cp -v /var/run/racoon/*.conf /etc/racoon/remote
sudo sed -i.bak 's/lifetime time 3600 sec/lifetime time 168 hours/' /etc/racoon/remote/*.conf

echo 'Restarting Racoon'
sudo launchctl stop com.apple.racoon
sudo launchctl start com.apple.racoon
